### ISSUE TITLE
[Bug] Jellyfin now playing can't be disabled

### ISSUE THREAD

**Issue by henryxrl** [benphelps/homepage#1326]
### Description

I added the following two lines to my Jellyfin widget:

```
enableNowPlaying: false # optional, defaults to true
enableBlocks: true # optional, defaults to false
```

My intention was to disable the now playing portion and only let the media count portion show. But no matter what I do, now playing always show up.

### Steps to reproduce

1. Add the aforementioned lines to Jellyfin widget
2. Save the file and refresh the webpage
3. Now playing still shows

### homepage version

v0.6.15

### Installation method

Docker

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
```
          widget:
               type: jellyfin
               ...
               enableNowPlaying: false
               enableBlocks: true
```

<img width="496" alt="Screenshot 2023-04-06 at 8 02 21 PM" src="https://user-images.githubusercontent.com/4887959/230532711-2093ca7d-12a9-46e9-bb31-684e9452e6ce.png">

Please double-check youre running the latest version (.15)?

I did notice an issue with using docker labels, but I've fixed that already and it doesn't look like that applies here?

**Comment by henryxrl** [comment]
Hmm it was the latest version, v0.6.15.

At the end I was able to fix it by creating a new docker instance - restarting didn't fix it for me.

**Comment by shamoon** [comment]
Cool. Yea restart ≠ recreate
