### ISSUE TITLE
[Bug] Pyload Widget

### ISSUE THREAD

**Issue by Nonoss117** [benphelps/homepage#517]
### Description

I use pyload-ng docker.

I get an API error with Pyload widget. 
![image](https://user-images.githubusercontent.com/79055577/201116940-71406642-2313-4e1c-8922-e8a4f55c59cf.png)

I created a user with "LIST" permissions (I also tried with an admin user)

my `services.yaml`:
``` yaml
    - Pyload-ng:
        icon: pyload.png
        href: http://192.168.1.100:8100/
        server: nas-docker
        container: pyload-ng
        description: Téléchargements
        widget:
            type: pyload
            fields: ["speed", "active", "queue", "total"]
            url: http://192.168.1.100:8100
            username: monitor
            password: My.password
```
My log file :
[homepage-main.log](https://github.com/benphelps/homepage/files/9981663/homepage-main.log)

Is there something wrong with my parameters ?
Or the widget is only ok for pyload and not for pyload-ng ?

### Steps to reproduce

same configuration, with docker `pyload-ng`

### homepage version

main (eff2f1a, 10 nov. 2022)

### Installation method

Docker

### Configuration

```yaml
Unraid + linuxserver/docker-pyload-ng
```

**Comment by Nonoss117** [comment]
Ah it's a challenge for me lol.
Is it the right command ?
`curl -L -k http://192.168.1.100:8100/api/`

in a shell window ?

**Comment by shamoon** [comment]
No, its not so easy for pyload, first:

`curl -L -X POST -H "Content-Type:application/x-www-form-urlencoded" -d "username=USERNAME&password=PASSWORD" http://192.168.1.100:8100/api/login`

which should return a session ID, then:

`curl -L -X POST -H "Content-Type:application/x-www-form-urlencoded" -d "session=SESSIONID" http://192.168.1.100:8100/api/statusServer`

**Comment by Nonoss117** [comment]
Thank's for your help shamoon.
This is the result : 
`root@Nas:~# curl -L -X POST -H "Content-Type:application/x-www-form-urlencoded" -d "username=monitor&password=xxxxxx" http://192.168.1.100:8100/api/login
{"_flashes":[["message","Logged in successfully"]],"_permanent":true,"authenticated":true,"id":3,"name":"monitor","perms":16,"role":1,"template":"default"}

root@Nas:~# ^C

root@Nas:~# curl -L -X POST -H "Content-Type:application/x-www-form-urlencoded" -d "session=3" http://192.168.1.100:8100/api/statusServer
{"error":"Unauthorized"}`

I tried with my admin account, same : `{"error":"Unauthorized"}`

**Comment by shamoon** [comment]
Hmm, that is odd its a pretty different output. Im not overly familiar with the project (besides testing) but are you using https://github.com/pyload/pyload --> https://github.com/linuxserver/docker-pyload i.e. lscr.io/linuxserver/pyload ?

**Comment by shamoon** [comment]
Oh weird, theres https://github.com/linuxserver/docker-pyload and https://github.com/linuxserver/docker-pyload-ng . Im not sure what the difference is

**Comment by shamoon** [comment]
Ah, thanks for the explanation. Its a little confusing to figure that out online. Anyway I figured out that the -ng API returns the session in a cookie and requires it as such, totally different than non-ng. 

I believe this is fixed now and the widget should work for both, please let me know!

**Comment by Nonoss117** [comment]
Yeah, works fine now

![image](https://user-images.githubusercontent.com/79055577/201295217-03862378-2c85-43d5-97a5-8961cb27455d.png)

Thank you @shamoon  :-)

**Comment by Nonoss117** [comment]
@shamoon 
Hm, no luck. Now there's an api error.

I updated homepage to nightly (3c0b185, 11 nov. 2022), refreshed the page, made some tests. Everything was ok (see my screen capture above).
But now, after a few time, same a before, API error.
I didn't change anything. It's a mystery for me.

**Comment by Nonoss117** [comment]
In complement.
I restart homepage docker container.
The widget is ok.
1 hour after the restart, the API error is back again.

**Comment by Nonoss117** [comment]
The report of the command :
active	0
captcha	false
download	true
pause	false
queue	0
reconnect	false
speed	0
total	0

The strange thing is that after a few times, the API returns ok. But I wasn't behind my screen.

The API is ok for this report

**Comment by Nonoss117** [comment]
Ah this is the report with API error :

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object

**Comment by Nonoss117** [comment]
It's crazy, lol
During 1 hour : API ok
Then during 1 hour : API error
Then API ok ....
and so on

without doing anything

**Comment by shamoon** [comment]
Its a weird API tbh, it does things like return status 200 (normal) even on login failure. I just pushed another change (takes a bit of time to build) that might at least make the error output for you more helpful. But also I would suggest re-creating the container and see if that helps with the intermittent thing.

If you are still getting it with the newer version, please check the logs (docker) and the same network call output as above again.

**Comment by Nonoss117** [comment]
With your last widget update, no more API error.
Everything seems to be ok.

Thanks shamoon 👍
